[package]
name = "nu_plugin_plist"
description = "Plist parsing for nushell"
version = "0.1.4"
edition = "2021"
license = "MIT"


[dependencies]
plist = "^1.4"
nu-plugin = "^0.80"
nu-protocol = "^0.80"
chrono = "^0.4"
